name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ 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 }}
        issue-message: "Thanks for raising first issue on this repo. Happy coding! 🚀' first issue"
        pr-message: "Hurray! U have just made a new pull request for the repository we will be review the pr soon. Happy coding! 🚀' first pull request"
